### ISSUE TITLE
Monitor scaling cuts off graph canvas

### ISSUE THREAD

**Issue by marhkb** [Sjoerd1993/Graphs#259] opened 2023-05-09 15:03 UTC
The graph is cut off if I set my monitor scale factor to 200%. See this video.

[Bildschirmaufzeichnung vom 2023-05-09, 16-56-24.webm](https://github.com/Sjoerd1993/Graphs/assets/3630213/bac0172c-3afd-4d7a-8533-148d9f7f7928)

It seems:
200% -> allocates 1/2 of the available height
300% -> allocates 1/3 of the available height
...

**Comment by Sjoerd1993** [comment] 2023-05-09 15:46
So a quick update on this, it seems to be an upstream issue with the matplotlib backend that is being used. If I switch it out from gtk4cairo to gtk4agg, this issue solves itself. However, we switched to gtk4cairo because gtk4agg has another issue, there's a clear white flickering when rescaling in dark mode (it's there in light mode as well, but it's less noticable). Furthermore, gtk4cairo has a clearly better performance as well.  See attached video with the (working) gtk4agg backend.

One non-ideal solution as a temporary workaround is maybe to set the backend as an option in the preferences. Maybe that @cmkohnen has some ideas. I'll also try to see if I can get in contact upstream to see if either of these issues have known fixes.

[Schermopname van 2023-05-09 17-35-46.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/852c4fa3-c403-4c2a-93c4-5d3c32c94fcb)

**Comment by Sjoerd1993** [comment] 2023-05-09 15:47
Just as an FYI, as it doesn't show in the video. It does actually scale correctly in the gtk4agg backend, it doesn't stay white. It flickers white while dragging, and general performance is worse during that action.

**Comment by Sjoerd1993** [comment] 2023-05-10 08:59
It installs fine on my Fedora 36 toolbox with pip, but not on my Fedora 38 toolbox nor with the Flatpak. Not exactly sure what the issue is, will try a bit more later. The wheel works fine as well, but lacks an amd64 build.

I've filed an issue upstream about this scaling (it's an upstream bug in the gtk4cairo backend, and is easy to reproduce from the CLI with a few lines of code), as well as about the seemingly broken pip install in modern Fedora versions for mplcairo.

**Comment by Sjoerd1993** [comment] 2023-05-10 11:32
Another update on this issue, I've got mplcairo to compile from source, the trick is that it somehow needs network access during build-time for some reason. Not sure if this is acceptable on Flathub though. But it works with the following relevant part in the manifest:

 ```
           "name": "python3-mplcairo",
            "buildsystem": "simple",
	"build-options": {
		"build-args": [ "--share=network" ]
	},            
            "build-commands": [
 		   "pip3 install --verbose --exists-action=i --no-index --find-links=\"file://${PWD}\" --prefix=${FLATPAK_DEST} \"mplcairo\" --no-build-isolation"
            ],
            "sources": [
                {
		      "type": "file",
		      "url": "https://files.pythonhosted.org/packages/73/4c/d30237614ad1c6e7b6987346e72c60db61145a09e09dd8ff28217da390db/mplcairo-0.5.tar.gz",
		      "sha256": "3d2595431ec968399ac8d63ea4b6f35baecdd071a14a031d178da3cc83fe652e"
                }
            ]
```

Will check with Flathub if this is an acceptable thing to do however before publishing that as a PR. Also, if Matplotlib fixes this upstream in the bundled cairo backend, I will probably switch to that at that point. Even if it's only to reduce the amount of dependencies.

Thanks @marhkb again for reporting this bug, as I would never have noticed it given my screen dpi (1440p on 27" and 1080p on 15") is too low to really need scaling. A bit of an unrelated comment but seeing the screencast in the original post, I can also see how fractional scaling support would be nice to have in GTK. As 100% indeed seems to small, but 200% is a bit too big imo.

**Comment by Sjoerd1993** [comment] 2023-05-10 11:58
Build arguments are indeed not allowed on Flathub, so bundling it like this is not the solution. Perhaps I should try to see if it's possible to create some wheels for the aarch64 build, maybe I can get access to some workflow environment somewhere..

**Comment by marhkb** [comment] 2023-05-10 18:11
> Thanks @marhkb again for reporting this bug, as I would never have noticed it given my screen dpi (1440p on 27" and 1080p on 15") is too low to really need scaling. A bit of an unrelated comment but seeing the screencast in the original post, I can also see how fractional scaling support would be nice to have in GTK. As 100% indeed seems to small, but 200% is a bit too big imo.

You're welcome. Yeah, I somehow regret I didn't buy a 5K screen. 200% scaling would be perfect in this case. Also, I can't use `scale-monitor-framebuffer` because that makes XWayland apps blurry. Guess I still have to wait a few years. :shrug:

**Comment by Sjoerd1993** [comment] 2023-05-11 10:56
Just to give another update on this, this is apparently a regression bug that was introduces somewhere between the migration from Matplotlib 3.5.3 to 3.6.0. See related issue https://github.com/matplotlib/matplotlib/issues/25847

Unfortunately, the way matplotlib 3.5.x handles CSS is incompatible with Gtk4.10, so just downgrading to that is not directly straight-forward. The fix is relatively easy though and  I've got a fork of matplotlib on my GH where the fix is back-ported to matplotlib 3.5.3, but I've not been able to completely install matplotlib from source in the manifest. The issue is that it tries to install the freetype packages, for which it needs network access. Granting it network access during compilation works, but is not allowed on Flathub. I haven't been able to bundle these freetype packages offline either, and will look at it further at a later time.

**Comment by Sjoerd1993** [comment] 2023-05-11 12:51
I've submitted a fix to this to Matplotlib upstream: https://github.com/matplotlib/matplotlib/pull/25861
Not sure when it will land in a stable Matplotlib version on PyPi if it gets accepted. But at least it's good to know that it's a relatively easy fix.

**Comment by cmkohnen** [comment] 2023-05-11 15:54
Since we are inheriting from the very class your upstream fix targets, we could just temporarily overwrite the `on_draw_event()` function with an implementation that fixes this issue

**Comment by Sjoerd1993** [comment] 2023-05-11 18:49
That's brilliant, that indeed works perfectly!

That's a really nice workaround until it's fixed in the upstream and released in the stable Matplotlib, preparing a PR now.

**Closed** 2023-05-12 07:07 UTC
Labels: bug

**Comment by Sjoerd1993** [comment] 2023-05-12 07:14
Thanks for the suggestions and bug reports. This issue should be fixed (at least in Graphs) with the next release!
